package uk.ac.uwl.luci.hb;
// Generated Mar 9, 2012 6:53:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Contacts generated by hbm2java
 */
public class Contacts  implements java.io.Serializable {


     private int contactId;
     private String contactName;
     private String contactTel;
     private String contactEmail;
     private String contactAddress;
     private Boolean isActive;

    public Contacts() {
    }

	
    public Contacts(int contactId) {
        this.contactId = contactId;
    }
    public Contacts(int contactId, String contactName, String contactTel, String contactEmail, String contactAddress, Boolean isActive) {
       this.contactId = contactId;
       this.contactName = contactName;
       this.contactTel = contactTel;
       this.contactEmail = contactEmail;
       this.contactAddress = contactAddress;
       this.isActive = isActive;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactTel() {
        return this.contactTel;
    }
    
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getContactAddress() {
        return this.contactAddress;
    }
    
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


