package uk.ac.uwl.luci.hb;
// Generated Mar 9, 2012 6:53:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Contacts generated by hbm2java
 */
public class Enquiries  implements java.io.Serializable {


     private int enquiriesID;
     private String enquiryContact;
     private String enquiryTel;
     private String enquiryEmail;

    public Enquiries() {
    }

	
    public Enquiries(int enquiriesID) {
        this.enquiriesID = enquiriesID;
    }
    public Enquiries(int enquiriesID, String enquiryContact, String enquiryTel, String enquiryEmail) {
       this.enquiriesID = enquiriesID;
       this.enquiryContact = enquiryContact;
       this.enquiryTel = enquiryTel;
       this.enquiryEmail = enquiryEmail;
    }

    public int getEnquiriesID() {
        return enquiriesID;
    }

    public String getEnquiryContact() {
        return enquiryContact;
    }

    public String getEnquiryTel() {
        return enquiryTel;
    }

    public String getEnquiryEmail() {
        return enquiryEmail;
    }

    public void setEnquiriesID(int enquiriesID) {
        this.enquiriesID = enquiriesID;
    }

    public void setEnquiryContact(String enquiryContact) {
        this.enquiryContact = enquiryContact;
    }

    public void setEnquiryTel(String enquiryTel) {
        this.enquiryTel = enquiryTel;
    }

    public void setEnquiryEmail(String enquiryEmail) {
        this.enquiryEmail = enquiryEmail;
    }
    
    
   

}


