package uk.ac.uwl.luci.hb;
// Generated Mar 9, 2012 6:53:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * XcriCourseinstance generated by hbm2java
 */
public class XcriCourseinstance  implements java.io.Serializable {


    public void setWorkExperience(String workExperience)
    {
        this.workExperience = workExperience;
    }

    public void setExtraStudy(String extraStudy)
    {
        this.extraStudy = extraStudy;
    }

    public void setEntrySkills(String entrySkills)
    {
        this.entrySkills = entrySkills;
    }

    public void setStudentSupport(String studentSupport)
    {
        this.studentSupport = studentSupport;
    }

    public String getWorkExperience()
    {
        return workExperience;
    }

    public String getExtraStudy()
    {
        return extraStudy;
    }

    public String getEntrySkills()
    {
        return entrySkills;
    }

    public String getStudentSupport()
    {
        return studentSupport;
    }

    public void setIntExamFees(String intExamFees)
    {
        this.intExamFees = intExamFees;
    }

    public void setFeeNotes(String feeNotes)
    {
        this.feeNotes = feeNotes;
    }

    public String getIntExamFees()
    {
        return intExamFees;
    }

    public String getFeeNotes()
    {
        return feeNotes;
    }

    public void setDurationNotes(String durationNotes)
    {
        this.durationNotes = durationNotes;
    }

    public void setDayTaught(String dayTaught)
    {
        this.dayTaught = dayTaught;
    }

    public void setTimeTaught(String timeTaught)
    {
        this.timeTaught = timeTaught;
    }

    public String getDurationNotes()
    {
        return durationNotes;
    }

    public String getDayTaught()
    {
        return dayTaught;
    }

    public String getTimeTaught()
    {
        return timeTaught;
    }

    public XcriCourseinstance()
    {
    }

    public XcriCourseinstance(int courseInstanceId)
    {
        this.courseInstanceId = courseInstanceId;
    }

    public XcriCourseinstance(int courseInstanceId, Integer courseId, String courseTitle, String courseCode, Integer locationId, String studyModeDesc, String durationWeeks, 
            Date startDate, Date esstartDate, Date endDate, Date esendDate, String entryCriteria, Integer acadContactId, Integer acadContactId1, 
            Integer acadContactId2, Integer acadContactId3, String applicationUrl, Boolean isActive, String homeFees, String overseasFees, String siteName, 
            Integer addressId, String telephone, String fax, String exams, String courseWork, String materialFee, String additionalCosts, 
            String examFee, String concessionFees, String fee, String details, String ucascode, String ucascodeB, String internationalEntryCriteria, 
            String interview, Integer feeId, String homeFees2, String overseasFees2, String durationNotes, String dayTaught, String timeTaught, 
            String intExamFees, String feeNotes, String workExperience, String extraStudy, String entrySkills, String studentSupport)
    {
        this.workExperience = workExperience;
        this.extraStudy = extraStudy;
        this.entrySkills = entrySkills;
        this.studentSupport = studentSupport;
        this.courseInstanceId = courseInstanceId;
        this.courseId = courseId;
        this.courseTitle = courseTitle;
        this.courseCode = courseCode;
        this.locationId = locationId;
        this.studyModeDesc = studyModeDesc;
        this.durationWeeks = durationWeeks;
        this.startDate = startDate;
        this.esstartDate = esstartDate;
        this.endDate = endDate;
        this.esendDate = esendDate;
        this.entryCriteria = entryCriteria;
        this.acadContactId = acadContactId;
        this.acadContactId1 = acadContactId1;
        this.acadContactId2 = acadContactId2;
        this.acadContactId3 = acadContactId3;
        this.applicationUrl = applicationUrl;
        this.isActive = isActive;
        this.homeFees = homeFees;
        this.overseasFees = overseasFees;
        this.siteName = siteName;
        this.addressId = addressId;
        this.telephone = telephone;
        this.fax = fax;
        this.exams = exams;
        this.courseWork = courseWork;
        this.materialFee = materialFee;
        this.additionalCosts = additionalCosts;
        this.examFee = examFee;
        this.concessionFees = concessionFees;
        this.fee = fee;
        this.details = details;
        this.ucascode = ucascode;
        this.ucascodeB = ucascodeB;
        this.internationalEntryCriteria = internationalEntryCriteria;
        this.interview = interview;
        this.feeId = feeId;
        this.homeFees2 = homeFees2;
        this.overseasFees2 = overseasFees2;
        this.durationNotes = durationNotes;
        this.dayTaught = dayTaught;
        this.timeTaught = timeTaught;
        this.intExamFees = intExamFees;
        this.feeNotes = feeNotes;
    }

    public int getCourseInstanceId()
    {
        return courseInstanceId;
    }

    public void setCourseInstanceId(int courseInstanceId)
    {
        this.courseInstanceId = courseInstanceId;
    }

    public Integer getCourseId()
    {
        return courseId;
    }

    public void setCourseId(Integer courseId)
    {
        this.courseId = courseId;
    }

    public String getCourseTitle()
    {
        return courseTitle;
    }

    public void setCourseTitle(String courseTitle)
    {
        this.courseTitle = courseTitle;
    }

    public String getCourseCode()
    {
        return courseCode;
    }

    public void setCourseCode(String courseCode)
    {
        this.courseCode = courseCode;
    }

    public Integer getLocationId()
    {
        return locationId;
    }

    public void setLocationId(Integer locationId)
    {
        this.locationId = locationId;
    }

    public String getStudyModeDesc()
    {
        return studyModeDesc;
    }

    public void setStudyModeDesc(String studyModeDesc)
    {
        this.studyModeDesc = studyModeDesc;
    }

    public String getDurationWeeks()
    {
        return durationWeeks;
    }

    public void setDurationWeeks(String durationWeeks)
    {
        this.durationWeeks = durationWeeks;
    }

    public Date getStartDate()
    {
        return startDate;
    }

    public void setStartDate(Date startDate)
    {
        this.startDate = startDate;
    }

    public Date getEsstartDate()
    {
        return esstartDate;
    }

    public void setEsstartDate(Date esstartDate)
    {
        this.esstartDate = esstartDate;
    }

    public Date getEndDate()
    {
        return endDate;
    }

    public void setEndDate(Date endDate)
    {
        this.endDate = endDate;
    }

    public Date getEsendDate()
    {
        return esendDate;
    }

    public void setEsendDate(Date esendDate)
    {
        this.esendDate = esendDate;
    }

    public String getEntryCriteria()
    {
        return entryCriteria;
    }

    public void setEntryCriteria(String entryCriteria)
    {
        this.entryCriteria = entryCriteria;
    }

    public Integer getAcadContactId()
    {
        return acadContactId;
    }

    public void setAcadContactId(Integer acadContactId)
    {
        this.acadContactId = acadContactId;
    }

    public Integer getAcadContactId1()
    {
        return acadContactId1;
    }

    public void setAcadContactId1(Integer acadContactId1)
    {
        this.acadContactId1 = acadContactId1;
    }

    public Integer getAcadContactId2()
    {
        return acadContactId2;
    }

    public void setAcadContactId2(Integer acadContactId2)
    {
        this.acadContactId2 = acadContactId2;
    }

    public Integer getAcadContactId3()
    {
        return acadContactId3;
    }

    public void setAcadContactId3(Integer acadContactId3)
    {
        this.acadContactId3 = acadContactId3;
    }

    public String getApplicationUrl()
    {
        return applicationUrl;
    }

    public void setApplicationUrl(String applicationUrl)
    {
        this.applicationUrl = applicationUrl;
    }

    public Boolean getIsActive()
    {
        return isActive;
    }

    public void setIsActive(Boolean isActive)
    {
        this.isActive = isActive;
    }

    public String getHomeFees()
    {
        return homeFees;
    }

    public void setHomeFees(String homeFees)
    {
        this.homeFees = homeFees;
    }

    public String getOverseasFees()
    {
        return overseasFees;
    }

    public void setOverseasFees(String overseasFees)
    {
        this.overseasFees = overseasFees;
    }

    public String getSiteName()
    {
        return siteName;
    }

    public void setSiteName(String siteName)
    {
        this.siteName = siteName;
    }

    public Integer getAddressId()
    {
        return addressId;
    }

    public void setAddressId(Integer addressId)
    {
        this.addressId = addressId;
    }

    public String getTelephone()
    {
        return telephone;
    }

    public void setTelephone(String telephone)
    {
        this.telephone = telephone;
    }

    public String getFax()
    {
        return fax;
    }

    public void setFax(String fax)
    {
        this.fax = fax;
    }

    public String getExams()
    {
        return exams;
    }

    public void setExams(String exams)
    {
        this.exams = exams;
    }

    public String getCourseWork()
    {
        return courseWork;
    }

    public void setCourseWork(String courseWork)
    {
        this.courseWork = courseWork;
    }

    public String getMaterialFee()
    {
        return materialFee;
    }

    public void setMaterialFee(String materialFee)
    {
        this.materialFee = materialFee;
    }

    public String getAdditionalCosts()
    {
        return additionalCosts;
    }

    public void setAdditionalCosts(String additionalCosts)
    {
        this.additionalCosts = additionalCosts;
    }

    public String getExamFee()
    {
        return examFee;
    }

    public void setExamFee(String examFee)
    {
        this.examFee = examFee;
    }

    public String getConcessionFees()
    {
        return concessionFees;
    }

    public void setConcessionFees(String concessionFees)
    {
        this.concessionFees = concessionFees;
    }

    public String getFee()
    {
        return fee;
    }

    public void setFee(String fee)
    {
        this.fee = fee;
    }

    public String getDetails()
    {
        return details;
    }

    public void setDetails(String details)
    {
        this.details = details;
    }

    public String getUcascode()
    {
        return ucascode;
    }

    public void setUcascode(String ucascode)
    {
        this.ucascode = ucascode;
    }

    public String getUcascodeB()
    {
        return ucascodeB;
    }

    public void setUcascodeB(String ucascodeB)
    {
        this.ucascodeB = ucascodeB;
    }

    public String getInternationalEntryCriteria()
    {
        return internationalEntryCriteria;
    }

    public void setInternationalEntryCriteria(String internationalEntryCriteria)
    {
        this.internationalEntryCriteria = internationalEntryCriteria;
    }

    public String getInterview()
    {
        return interview;
    }

    public void setInterview(String interview)
    {
        this.interview = interview;
    }

    public Integer getFeeId()
    {
        return feeId;
    }

    public void setFeeId(Integer feeId)
    {
        this.feeId = feeId;
    }

    public String getHomeFees2()
    {
        return homeFees2;
    }

    public void setHomeFees2(String homeFees2)
    {
        this.homeFees2 = homeFees2;
    }

    public String getOverseasFees2()
    {
        return overseasFees2;
    }

    public void setOverseasFees2(String overseasFees2)
    {
        this.overseasFees2 = overseasFees2;
    }

    private int courseInstanceId;
    private Integer courseId;
    private String courseTitle;
    private String courseCode;
    private Integer locationId;
    private String studyModeDesc;
    private String durationWeeks;
    private Date startDate;
    private Date esstartDate;
    private Date endDate;
    private Date esendDate;
    private String entryCriteria;
    private Integer acadContactId;
    private Integer acadContactId1;
    private Integer acadContactId2;
    private Integer acadContactId3;
    private String applicationUrl;
    private Boolean isActive;
    private String homeFees;
    private String overseasFees;
    private String siteName;
    private Integer addressId;
    private String telephone;
    private String fax;
    private String exams;
    private String courseWork;
    private String materialFee;
    private String additionalCosts;
    private String examFee;
    private String concessionFees;
    private String fee;
    private String details;
    private String ucascode;
    private String ucascodeB;
    private String internationalEntryCriteria;
    private String interview;
    private Integer feeId;
    private String homeFees2;
    private String overseasFees2;
    private String intExamFees;
    private String workExperience;
    private String extraStudy;
    private String entrySkills;
    private String studentSupport;
    private String feeNotes;
    private String durationNotes;
    private String dayTaught;
    private String timeTaught;

}


