package uk.ac.uwl.luci.hb;
// Generated Mar 9, 2012 6:53:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private int addressId;
     private String addressName;
     private String address1;
     private String address2;
     private String address3;
     private String address4;
     private String postcode;
     private String directionsUrl;
     private String mapUrl;
     private Boolean isActive;
     private String esid;
     private String rsid;

    public Address() {
    }

	
    public Address(int addressId) {
        this.addressId = addressId;
    }
    public Address(int addressId, String addressName, String address1, String address2, String address3, String address4, String postcode, String directionsUrl, String mapUrl, Boolean isActive, String esid, String rsid) {
       this.addressId = addressId;
       this.addressName = addressName;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.address4 = address4;
       this.postcode = postcode;
       this.directionsUrl = directionsUrl;
       this.mapUrl = mapUrl;
       this.isActive = isActive;
       this.esid = esid;
       this.rsid = rsid;
    }
   
    public int getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }
    public String getAddressName() {
        return this.addressName;
    }
    
    public void setAddressName(String addressName) {
        this.addressName = addressName;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getDirectionsUrl() {
        return this.directionsUrl;
    }
    
    public void setDirectionsUrl(String directionsUrl) {
        this.directionsUrl = directionsUrl;
    }
    public String getMapUrl() {
        return this.mapUrl;
    }
    
    public void setMapUrl(String mapUrl) {
        this.mapUrl = mapUrl;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public String getEsid() {
        return this.esid;
    }
    
    public void setEsid(String esid) {
        this.esid = esid;
    }
    public String getRsid() {
        return this.rsid;
    }
    
    public void setRsid(String rsid) {
        this.rsid = rsid;
    }




}


