package uk.ac.uwl.luci.hb;
// Generated Mar 9, 2012 6:53:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Subjects generated by hbm2java
 */
public class Subjects  implements java.io.Serializable {


     private int subjectId;
     private Integer rsubjectId;
     private Integer essubjectId;
     private String subject;
     private Boolean showInMain;
     private Boolean showInFhhs;
     private Boolean showInTrusts;
     private Boolean isActive;
     private Integer relatedSubjectId;

    public Subjects() {
    }

	
    public Subjects(int subjectId) {
        this.subjectId = subjectId;
    }
    public Subjects(int subjectId, Integer rsubjectId, Integer essubjectId, String subject, Boolean showInMain, Boolean showInFhhs, Boolean showInTrusts, Boolean isActive, Integer relatedSubjectId) {
       this.subjectId = subjectId;
       this.rsubjectId = rsubjectId;
       this.essubjectId = essubjectId;
       this.subject = subject;
       this.showInMain = showInMain;
       this.showInFhhs = showInFhhs;
       this.showInTrusts = showInTrusts;
       this.isActive = isActive;
       this.relatedSubjectId = relatedSubjectId;
    }
   
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }
    public Integer getRsubjectId() {
        return this.rsubjectId;
    }
    
    public void setRsubjectId(Integer rsubjectId) {
        this.rsubjectId = rsubjectId;
    }
    public Integer getEssubjectId() {
        return this.essubjectId;
    }
    
    public void setEssubjectId(Integer essubjectId) {
        this.essubjectId = essubjectId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public Boolean getShowInMain() {
        return this.showInMain;
    }
    
    public void setShowInMain(Boolean showInMain) {
        this.showInMain = showInMain;
    }
    public Boolean getShowInFhhs() {
        return this.showInFhhs;
    }
    
    public void setShowInFhhs(Boolean showInFhhs) {
        this.showInFhhs = showInFhhs;
    }
    public Boolean getShowInTrusts() {
        return this.showInTrusts;
    }
    
    public void setShowInTrusts(Boolean showInTrusts) {
        this.showInTrusts = showInTrusts;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Integer getRelatedSubjectId() {
        return this.relatedSubjectId;
    }
    
    public void setRelatedSubjectId(Integer relatedSubjectId) {
        this.relatedSubjectId = relatedSubjectId;
    }




}


